apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmctl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmctl-cluster-admin
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: vmctl
  namespace: default
---
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: have-podinfo
spec:
  selector:
    matchLabels:
      app: vmctl
  volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
        - path: "name"
          fieldRef:
            fieldPath: metadata.name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmctl
  labels:
    app: vmctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmctl
  template:
    metadata:
      labels:
        app: vmctl
    spec:
      containers:
      - name: vmctl
        image: quay.io/fabiand/vmctl
        imagePullPolicy: IfNotPresent
        args:
        - "testvm"
      serviceAccountName: vmctl
