apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmctl
  labels:
    app: vmctl
spec:
  replicas: 0
  selector:
    matchLabels:
      app: vmctl
  template:
    metadata:
      labels:
        app: vmctl
    spec:
      containers:
      - name: vmctl
        image: quay.io/fabiand/vmctl
        args:
        - "testvm"
